Atividade 1:

Crie um array unidimenssional com os numeros de 1 a 12. Transforme este array em uma matriz de 3 linhas e 4 colunas.

(DESAFIO: Aplique a trasnposição da matriz para criar as dimensões em 4X3 (.transpose) e, em seguida, crie um array unidimensional (.flatten)).

In [2]:
import pandas as pd
import numpy as np

In [3]:
#Resolução:
array_original= np.arange(1,13)
print(array_original)
array_3por_4 = array_original.reshape(3,4)
print(array_3por_4)
print('----------------------')

#DESAFIO
array_4por_3 = array_3por_4.transpose()


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------------------


Atividade 2:

Leia o arquivo ClassicDisco.csv trabalhado em aulas anteriores o comando .describe() para gerar uma aálise estatística prévia dos dados. Não esqueça dos comandos para vereficar as primeiras e últimas linhas do dataset como apoio nessa atividade.